### ISSUE TITLE
The most diabolical Python antipattern

### ISSUE THREAD

**Issue by cclauss** [rohan472000/Github-repo-extraction-GCP#5]
* https://peps.python.org/pep-0008/#programming-recommendations

When catching exceptions, mention specific exceptions whenever possible instead of using a bare `except:` clause:
```python
try:
    import platform_specific_module
except ImportError:
    platform_specific_module = None
```
A `bare except:` clause will catch `SystemExit` and `KeyboardInterrupt` exceptions, making it harder to interrupt a program with Control-C, and can disguise other problems. If you want to catch all exceptions that signal program errors, use `except Exception:` (bare except is equivalent to `except BaseException:`).

* https://pypi.org/project/flake8-bugbear/
__B001__: Do not use `bare except:`, it also catches unexpected events like memory errors, interrupts, system exit, and so on. 

* https://realpython.com/the-most-diabolical-python-antipattern

```python
try:
    client.get_table(table_ref)
except:
    client.create_table(bigquery.Table(table_ref, schema=schema))
```

**Comment by rohan472000** [comment]
yeah sure
